---
output:
  bookdown::pdf_document2:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- Note this section is Required -->

\doublespacing

The following individuals certify that they have read, and recommend to the Faculty of Graduate
and Postdoctoral Studies for acceptance, the dissertation entitled:

\vspace{5mm}


\noindent\underline{\makebox[6in][l]{Major sources of variation in placental DNA methylation}}  
\vspace{2mm}

submitted by \underline{Victor Yuan} in partial fulfillment of the requirements for

the degree of \noindent\underline{\makebox[5in][l]{Doctor of Philosophy}}  

in \noindent\underline{\makebox[5.8in][l]{Genome Sciences and Technology}}

\vspace{5mm}

**Examining Committee:**

\noindent\underline{\makebox[6in][l]{Dr. Wendy P. Robinson, Professor, Medical Genetics, UBC}}  Research Supervisor

\noindent\underline{\makebox[6in][l]{Dr. Alex G. Beristain, Associate Professor, Obstetrics and Gynaecology, UBC}}  
Supervisory Committee Member

\noindent\underline{\makebox[6in][l]{Dr. Michael Kobor, Professor, Medical Genetics, UBC}}  
Supervisory Committee Member

\noindent\underline{\makebox[6in][l]{Name of University Examiner}}  
University Examiner

\noindent\underline{\makebox[6in][l]{Name of University Examiner}}  
University Examiner

\noindent\underline{\makebox[6in][l]{Name of External Examiner}}  
External Examiner

\vspace{5mm}

**Additional Supervisory Committee Members:**

\noindent\underline{\makebox[6in][l]{Dr. Sara Mostafavi, Associate Professor, Paul G. Allen School of Computer Science and Engineering, UW}}  
Supervisory Committee Member
