---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- Remember, It can't be longer than 350 words! Currently way over-->

The functioning of the placenta is critical for the healthy development of the fetus during pregnancy. Many perinatal health outcomes have been linked to placental-specific alterations in DNA methylation (DNAm), an epigenetic modification that regulates gene expression. Placental DNAm studies are often carried out on a population level, i.e. including hundreds of samples. Researchers tend to account for covariates such as sex, gestational age, and environmental influences, as these factors have been shown to be associated with effects on DNAm. It is now well-appreciated that genetic ancestry, ethnicity, and cell composition can explain the majority of variation in DNAm. However, genetic ancestry, ethnicity and cell-specific variation in DNAm is largely uncharacterized in the human placenta.

Ethnicity, which is self-reported, is often used as a surrogate marker for genetic ancestry, which is based on genetic markers, in population-based genomic studies. Having self-reported ethnicity in DNAm studies is an asset, since genetically-determined ancestry is often unavailable. However, self-reported ethnicity is not always collected, inconsistently defined, and sometimes poorly correlated with genetic ancestry. Therefore, there is a need for a consistently-defined marker of ethnicity or genetic ancestry for placental DNAm studies. There are existing methods for inferring genetic ancestry or ethnicity from DNAm measured on the popular 450k DNAm array, but these approaches were developed in somatic tissues and may therefore not perform as well on placental data.

The etiology of many pregnancy-associated conditions involves abnormalities in cell-specific placental processes. Preeclampsia, fetal growth restriction, and placenta accrete can occur when trophoblast-mediated invasion and remodeling of maternal vasculature is defective. To date, most research has relied on cell culturing methods to investigate trophoblast function. However, findings from these in vitro studies are limited in their ability to generalize because they fail to account for the complex uterine environment that exists in vivo. Furthermore, the extent of which other cell populations in the placenta contribute to placental-mediated pathologies is highly likely, yet poorly understood. For example, fetally-derived macrophages such as Hofbauer cells are enriched in inflammatory conditions resulting from infection, but our understanding of their exact function and origins is rudimentary at best. Vessel and endothelial cells in the mesenchymal core of the chorionic villi are likely affected in pathologies associated with alterations in blood flow, but the relevance of these cells is often overlooked as well. There are significant gaps in our cell-specific understanding of placental biology, which will need to be addressed in order to understand the changes that occur under pathological conditions.

Because the placenta is made up of several cell types, each with a distinct DNAm signature, whole-tissue measurements are ultimately an average of the DNAm signatures of the constituent cell types, weighted by their respective frequency in the bulk tissue sample. Therefore, observing variation in DNAm in heterogenous tissues such as the placenta can be often attributed to variation in cell composition, rather than DNAm changes that occur in the constituent cell populations. Variation in cell composition can be accounted for using physical cell counting methods, but these approaches are often challenging in a solid tissue such as the placenta. Instead, researchers are often using DNAm itself to infer cell composition. These bioinformatic algorithms, called cellular deconvolution, rely on cell-specific reference DNAm profiles from constituent cell types. Cell-specific reference DNAm profiles are available for cell deconvolution in tissues such as adult blood, cord blood, brain, and buccal; but not the placenta. Therefore, the extent of confounding from cell composition variation in placental DNAm studies is poorly understood.
