---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- Remember, It can't be longer than 150 words! -->

The placenta is an important organ for a healthy pregnancy. 
DNA methylation is a molecular mark that helps the placenta control what genes are turned on and off. 
Past research indicates that DNAm is an important component of placental biology, and that when pregnancy complications occur, corresponding changes in DNAm can occur. 
However, our understanding of what controls placental DNAm itself is rudimentary. 
We need to understand what influences placental DNAm under normal, healthy conditions before we can understand it under other contexts like in disease. 
My thesis aims at understanding some of the major factors that influence placental DNAm.
Throughout my research, I have also developed several analysis tools to help future placental DNAm research. 
Ultimately, my research has contributed to our understanding of the molecular characteristics of the placenta, which in turn helps us understand the role of placental biology during pregnancy. 